/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "Counter16.h"
#include "Counter8.h"
#include "PRS8.h"
#include "SPIM.h"
#include "UART.h"

#endif
