/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "Counter16.h"
#include "Counter8.h"
#include "Counter8_DC.h"
#include "DUALADC8.h"
#include "PRS8.h"
#include "SPIM.h"
#include "UART.h"
#include "pga_adc_in_1.h"
#include "pga_adc_in_2.h"

#endif
